[workspace]
repository = "https://github.com/CodedMasonry/dynamic_signing"
resolver = "2"
members = ["windows_agent", "server"]
default-members = []

[profile.dev]
debug = 0

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
