cargo-features = ["codegen-backend"]
[package]
name = "hf_windows_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
goldberg = "0.1.0"
rustls = { version = "0.23.4", default-features = false, features = ["ring", "tls12", "std", "log"] }

[build-dependencies]
directories = "5.0.1"
rustls-pemfile = "2.1.1"
