cargo-features = ["codegen-backend"]
[package]
name = "how_far"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
goldberg = "0.1.0"